export const langs = {
    "en": {
        "Delivery Method": "Delivery Method",
        "Billing Method": "Billing Method",
        "Print bill": "Print bill",
        "Print delivery note": "Print delivery note",
        "eBay Offers": "eBay Offers",
        "Home": "Home",
        "ebay": "ebay",
        "Orders": "Orders",
        "Users": "Users",
        "Products": "Products",
        "Discounts": "Discounts",
        "Categories": "Categories",
        "Product types": "Product types",
        "Delivery": "Delivery",
        "Newsletter": "Newsletter",
        "Home slider": "Home slider",
        "Banners": "Banners",
        "Settings": "Settings",
        "LogOut": "Log out",
        "User": "User",
        "Change user": "Change user",
        "Name": "Name",
        "Email": "E-mail",
        "CustomerGroup": "Customer group",
        "EmailVerified": "Email verified",
        "SubscribeToNewsletter": "Subscribe to Newsletter",
        "Billing address": "Billing address",
        "FirstName": "First Name",
        "LastName": "Last Name",
        "Street": "Street",
        "Zipcode": "Zip code",
        "City": "City",
        "Country": "Country",
        "EMail": "E-Mail",
        "EMailBusiness": "Business E-Mail",
        "EMailPrivate": "Private E-Mail",
        "Phone": "Phone",
        "VATID": "VAT ID",
        "Company": "Company",
        "FiscalCode": "Fiscal Code",
        "Department": "Department",
        "Shipping address": "Shipping address",
        "SPEICHERN": "Speichern",
        "Dashboard": "Dashboard",
        "Website statistics": "Website statistics",
        "Active clients": "Active clients",
        "Website Visits": "Website visits",
        "Last 7 days": "Last 7 days",
        "Today": "Today",
        "Recent products views": "Recent products views",
        "Alias": "Alias",
        "All orders": "All orders",
        "Search": "Search",
        "Invoice Number": "Invoice Number",
        "Note": "Note",
        "Total": "Total",
        "Status": "Status",
        "Time": "Time",
        "Add product": "Add product",
        "All users": "All users",
        "All products": "All products",
        "Show products that can be listed on eBay": "Show products that can be listed on eBay",
        "Price": "Price",
        "StockLevel": "Stock level",
        "Product": "Product",
        "Change product": "Change product",
        "Artikelnummer": "Artikel nummer",
        "Produkt im Shop sichtbar": "Product visible in the shop",
        "IsPopular": "Popular",
        "Image": "Image",
        "Produktname": "Product name",
        "Listenpreis (Brutto)": "List price (gross)",
        "Steuerklasse": "Tax bracket",
        "Bestelleinheit": "Bestelleinheit",
        "Beschreibung": "Order unit",
        "Erweiterte Beschreibung": "Extended description",
        "Schlüsselwörter für Suche": "Keywords for search",
        "Wesentliche Merkmale": "Main features",
        "eBay Settings": "eBay Settings",
        "Category": "Category",
        "EBay description": "Ebay description",
        "Manufacturer": "Manufacturer",
        "ManufacturerSKU": "Manufacturer SKU",
        "ISBN": "ISBN",
        "UPC": "UPC",
        "EAN": "EAN",
        "Add discount": "Add discount",
        "All discounts": "All discounts",
        "Quantity": "Quantity",
        "Discount %": "Discount %",
        "Discount": "Discount",
        "Configure discount": "Configure discount",
        "Add category": "Add category",
        "All categories": "All categories",
        "Breadcrumb": "Breadcrumb",
        "Change category": "Change category",
        "Position": "Position",
        "Is Visible": "Is Visible",
        "Product type": "Product type",
        "Select attribute to edit": "Select attribute to edit",
        "New attribute": "New attribute",
        "Add delivery method": "Add delivery method",
        "Delivery methods": "Delivery methods",
        "Delivery method": "Delivery method",
        "Change delivery method": "Change delivery method",
        "Add newsletter": "Add newsletter",
        "All newsletters": "All newsletters",
        "Configure newsletter": "Configure newsletter",
        "Title": "Title",
        "Text": "Text",
        "Add slide": "Add slide",
        "All slides": "All slides",
        "Subtitle": "Subtitle",
        "Slide": "Slide",
        "Change slide": "Change slide",
        "Desktop image": "Desktop image",
        "Tablet image": "Tablet image",
        "Phone image": "Phone image",
        "Description": "Description",
        "Link": "Link",
        "Add banner": "Add banner",
        "All banners": "All banners",
        "Banner": "Banner",
        "Change banner": "Change banner",
        "Change settings": "Change settings"
    },
    "de": {
        "Are you sure you want to delete?": "Sind Sie sicher, dass Sie löschen möchten?",
        "Tax: ": "MwSt:",
        "Total: ":"Brutto:",
        "Subtotal: ":"Netto:",
        "Delivery Method:": "Zustellung:",
        "Billing Method:": "Abrechnung:",
        "Show products that are out of stock":"Produkte anzeigen, die nicht auf Lager sind",
        "Delivery Method": "Zustellung",
        "Billing Method": "Abrechnung",
        "Print bill": "Rechnung drucken",
        "Print delivery note": "Rechnung+Lieferschein drucken",
        "eBay Offers": "eBay Angebote",
        "Home": "Home",
        "ebay": "ebay",
        "Orders": "Aufträge",
        "Users": "Benutzer",
        "Products": "Produkte",
        "Discounts": "Rabatte",
        "Categories": "Kategorien",
        "Product types": "Produkttypen",
        "Delivery": "Lieferung",
        "Newsletter": "Newsletter",
        "Home slider": "Home Schieberegler",
        "Banners": "Banner",
        "Settings": "Die Einstellungen",
        "LogOut": "Ausloggen",
        "User": "Nutzer",
        "Change user": "Benutzer wechseln",
        "Name": "Name",
        "Email": "E-mail",
        "CustomerGroup": "Kundengruppe",
        "EmailVerified": "Email überprüft",
        "SubscribeToNewsletter": "Newsletter abonnieren",
        "Billing address": "Rechnungsadresse",
        "FirstName": "Vorname",
        "LastName": "Nachname",
        "Street": "Straße",
        "Zipcode": "Postleitzahl",
        "City": "Stadt",
        "Country": "Land",
        "EMail": "E-mail",
        "EMailBusiness": "Geschäftliche E-Mail",
        "EMailPrivate": "Private E-Mail",
        "Phone": "Telefon",
        "VATID": "Umsatzsteuer-ID",
        "Company": "Unternehmen",
        "FiscalCode": "Steuergesetzbuch",
        "Department": "Abteilung",
        "Shipping address": "Lieferanschrift",
        "SPEICHERN": "SPEICHERN",
        "Dashboard": "Instrumententafel",
        "Website statistics": "Website-Statistiken",
        "Active clients": "Aktive Kunden",
        "Website Visits": "Website-Besuche",
        "Last 7 days": "Letzten 7 Tage",
        "Today": "Heute",
        "Recent products views": "Zuletzt angesehene Produkte",
        "Alias": "Alias",
        "All orders": "Liste der Bestellungen",
        "Search": "Suche",
        "Invoice Number": "Rechnungsnummer",
        "Note": "Hinweis",
        "Total": "Gesamt",
        "Status": "Status",
        "Time": "Zeit",
        "Add product": "Produkt hinzufügen",
        "All users": "Liste der Benutzer",
        "All products": "Produktliste",
        "Show products that can be listed on eBay": "Zeige Produkte, die bei eBay gelistet werden können",
        "Price": "Preis",
        "StockLevel": "Lagerbestand",
        "Product": "Produkt",
        "Change product": "Produkt wechseln",
        "Artikelnummer": "Artikelnummer",
        "Produkt im Shop sichtbar": "Produkt im Shop sichtbar",
        "IsPopular": "Beliebt",
        "Image": "Image",
        "Produktname": "Produktname",
        "Listenpreis (Brutto)": "Listenpreis (Brutto)",
        "Steuerklasse": "Steuerklasse",
        "Bestelleinheit": "Bestelleinheit",
        "Beschreibung": "Beschreibung",
        "Erweiterte Beschreibung": "Erweiterte Beschreibung",
        "Schlüsselwörter für Suche": "Schlüsselwörter für Suche",
        "Wesentliche Merkmale": "Wesentliche Merkmale",
        "eBay Settings": "eBay-Einstellungen",
        "Category": "Kategorie",
        "EBay description": "Ebay-Beschreibung",
        "Manufacturer": "Manufacturer",
        "ManufacturerSKU": "Manufacturer SKU",
        "ISBN": "ISBN",
        "UPC": "UPC",
        "EAN": "EAN",
        "Add discount": "Rabatt hinzufügen",
        "All discounts": "Liste der Rabatte",
        "Quantity": "Menge",
        "Discount %": "Rabatt %",
        "Discount": "Rabatt",
        "Configure discount": "Rabatt konfigurieren",
        "Add category": "Kategorie hinzufügen",
        "All categories": "Liste der Kategorien",
        "Breadcrumb": "Breadcrumb",
        "Change category": "Kategorie wechseln",
        "Position": "Position",
        "Is Visible": "Ist sichtbar",
        "Product type": "Produktart",
        "Select attribute to edit": "Wählen Sie das zu bearbeitende Attribut aus",
        "New attribute": "Neues Attribut",
        "Add delivery method": "Lieferungsmethode hinzufügen",
        "Delivery methods": "Versandmethoden",
        "Delivery method": "Delivery method",
        "Change delivery method": "Change delivery method",
        "Add newsletter": "Newsletter hinzufügen",
        "All newsletters": "Liste der Newsletter",
        "Configure newsletter": "Newsletter konfigurieren",
        "Title": "Title",
        "Text": "Text",
        "Add slide": "Folie hinzufügen",
        "All slides": "Liste der Folien",
        "Subtitle": "Untertitel",
        "Slide": "Rutschen",
        "Change slide": "Folie wechseln",
        "Desktop image": "Desktop-Bild",
        "Tablet image": "Tablet-Bild",
        "Phone image": "Telefonbild",
        "Description": "Beschreibung",
        "Link": "Verknüpfung",
        "Add banner": "Banner hinzufügen",
        "All banners": "Liste der Banner",
        "Banner": "Banner",
        "Change banner": "Banner wechseln",
        "Change settings": "Einstellungen ändern"
    }
}